### ISSUE TITLE
multiple dropzones?

### ISSUE THREAD

**Issue by petergrice** [chienhungchen/droppabilly#1]
Big fan of this, thanks. Could it be extended to work with more than one target element? That seems like a common real-world scenario: the user has a "filing" choice to make about where to drop. Currently, calling droppabilly a second time overrides the first.

(Sorry if this is the wrong place to ask this, as I am new to github.)

**Comment by markusdrake** [comment]
@chienhungchen or @petergrice could you provide an example of multiple dropzones with this script? I, so far, have been unable to accomplish this. For example - iterating over multiple drop zones like this:

```
var drops = document.querySelectorAll(".drop");

[].forEach.call(drops, function(drop){

dropster = new Droppabilly(drop, {
                    dragstersClassName: 'drag',
                    over: function(drop, drag) {
                        document.getElementById('drop-info').innerHTML = 'over event triggered';
                    },
                    out: function(drop, drag) {
                        document.getElementById('drop-info').innerHTML = 'out event triggered';
                    },
                    drop: function(drop, drag) {
                        document.getElementById('drop-info').innerHTML = 'drop event triggered';
                    }
                });


})
```
