### ISSUE TITLE
dragsters vs. dragstersClassName

### ISSUE THREAD

**Issue by bryanbraun** [chienhungchen/droppabilly#3]
Setting `dragsters: 'my-class',` as specified in the README didn't work for me.

Then I looked up in the example and saw that it was setting the class to `dragstersClassName`.

Does the README need to be updated to say `dragstersClassName`?

**Comment by chienhungchen** [comment]
@bryanbraun looks like you're right. https://github.com/chienhungchen/droppabilly/commit/cd433287ccea4fee637894467b24fed8198433a8

Updated! Thanks!
